// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mainSidebar: [
    {
      type: 'category',
      label: 'Contribution',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'contribution',
        },
      ],
    },
    {
      type: 'category',
      label: 'crossplane-provider-btp',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'crossplane-provider-btp/docs',
        },
      ],
    },
    {
      type: 'category',
      label: 'crossplane-provider-hana',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'crossplane-provider-hana/docs',
        },
      ],
    },
    {
      type: 'category',
      label: 'crossplane-provider-cloudfoundry',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'crossplane-provider-cloudfoundry/docs',
        },
      ],
    },
    {
      type: 'category',
      label: 'xp-clifford',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'xp-clifford/docs',
        },
      ],
    },
    // To add a new submodule, copy the block above and adjust label and dirName, e.g.:
    // {
    //   type: 'category',
    //   label: 'crossplane-provider-xyz',
    //   collapsible: true,
    //   collapsed: true,
    //   items: [{ type: 'autogenerated', dirName: 'crossplane-provider-xyz/docs' }],
    // },
  ],
};

module.exports = sidebars;
