// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mainSidebar: [
    {
      type: 'category',
      label: 'Contribution',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'contribution',
        },
      ],
    },
    {
      type: 'category',
      label: 'crossplane-provider-btp',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'crossplane-provider-btp/docs',
        },
      ],
    },
    {
      type: 'category',
      label: 'crossplane-provider-hana',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'crossplane-provider-hana/docs',
        },
      ],
    },
  ],
};

module.exports = sidebars;